### ISSUE TITLE
training speed

### ISSUE THREAD

**Issue by DLluopf** [wmcnally/kapao#6]
In my V100 32 GB GPU，I just can train one epoch one hour. If training 500 epoch，need 500 hours？

**Comment by wmcnally** [comment]
Which model size? That could be accurate. Training is indeed quite slow. I recommend training on CrowdPose, it is much much faster.

**Comment by DLluopf** [comment]
I train kapao-M model. What is the bottleneck to  accelerate training speed？

**Comment by wmcnally** [comment]
Image size and the size of the dataset. You could reduce image size if you wanted to speed up training. You would get similar accuracy using an image size of 1024.

**Comment by DLluopf** [comment]
I have tried to pack the dataset to lmdb to accelerate I/O speed，but it seems doesn‘t work. I will try to use smaller image size to train.

**Comment by DLluopf** [comment]
Why this model need train 500 epochs? Model like DEKR or HigherHRNet just need to train about 140 epochs.

**Comment by wmcnally** [comment]
You could train for 300 epochs and get similar results.

**Comment by nikhilchh** [comment]
1- Is the big input size(1000px+) used because of the requirement to detect small humans in the images?
2- Do you think one could work with half the image size if they are only interested in large humans (>64x64 area)?

3- Why heatmap based approaches can work with half the image sizes giving similar(-5%) AP/AR numbers?

**Comment by wmcnally** [comment]
Our method also works with 640 input size, but it is less accurate. Generally, using larger input size provides higher accuracy.

**Comment by nikhilchh** [comment]
How come training is slower(relative of DEKR oe HigherHRNet) due to big input size but inference is faster(relative of DEKR oe HigherHRNet) ?

Assuming train data to be same for both.

**Comment by wmcnally** [comment]
Because using the same input size as DEKR and HigherHrNet, KAPAO is even faster still, so we can afford to use a larger input size and still be faster. 

KAPAO is more efficient because it saves a lot of post-processing time due to not using heatmaps (see Table 1 in the paper). The network itself is also much more efficient because it does not have to generate large heatmaps and it doesn’t use so many skip connections and parallel branches.
